### ISSUE TITLE
Syntax Error?

### ISSUE THREAD

**Issue by airfrance267286** [Ariakim-Taiyo/LiveryChanger#15]
Uncaught SyntaxError: Identifier 'i' has already been declared (VM242:1)

**Comment by Ariakim-Taiyo** [comment]
Should be fixed now.

**Comment by thinkgeofsgame** [comment]
still not working :
![image](https://user-images.githubusercontent.com/99663982/155884215-f7c7fdfd-9b84-4dbf-a686-12454c99c939.png)

**Comment by Ariakim-Taiyo** [comment]
Hmm, I’m not sure what’s going on since it works fine on my end. Open up the underlined “vm10049:1” and show me that.

**Comment by thinkgeofsgame** [comment]
ok

**Comment by thinkgeofsgame** [comment]
![image](https://user-images.githubusercontent.com/99663982/155886168-2ed5ad88-6cd3-4dae-9862-14f682735538.png)

**Comment by thinkgeofsgame** [comment]
i refreshed geofs website and pasted the code
and its shows VM346:1

**Comment by Ariakim-Taiyo** [comment]
Hmm, that’s strange. I will get to work on it.

**Comment by Ariakim-Taiyo** [comment]
Just to be sure, you’re only pasting the code in once per session? There shouldn’t be anything past the interval at the end of the code.

**Comment by thinkgeofsgame** [comment]
Yes @Ariakim-Taiyo yes i would paste the code once per session.

**Comment by Ariakim-Taiyo** [comment]
The code has been deobfuscated to prevent this issue. let me know if the issue persists
